<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FestivalBuddy_BLL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FestivalBuddy Common\FestivalBuddy Common.csproj" />
    <ProjectReference Include="..\FestivalBuddy DAL\FestivalBuddy DAL.csproj" />
  </ItemGroup>

</Project>
